query ActiveWorkout {
    activeWorkout {
        id
        title
        description
        workoutParts {
            id
            title
            description
            exercise {
                id
                title
            }
            weight
            repetitionsNumber
            sortOrder
            completed
        }
        status
        date
    }
}

